sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
    - docker build -t fab_sshd_ubuntu tests/
install:
    - pip install fabric
    - pip install nose
script:
    - nosetests -v
