sudo: required
language: python
python:
  - "2.7"
services:
  - docker
before_install:
    - docker build -t fab_sshd_ubuntu -f tests/Dockerfile.apt .
install:
    - pip install fabric
    - pip install nose
    - pip install coverage
script:
    - sudo service docker restart; sleep 10
    - nosetests -v --with-coverage
after_success:
    - bash <(curl -s https://codecov.io/bash)
