FROM ubuntu:14.04
MAINTAINER Andrew Starr-Bochicchio <a.starr.b@gmail.com>

RUN apt-get update && apt-get install -y openssh-server sudo
RUN mkdir /var/run/sshd
RUN echo 'root:functionaltests' |chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN echo 'deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse' > /etc/apt/sources.list.d/trusty-backports.list

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
